language: python
python:
- '3.6'

install:
- python -m pip install -r requirements.txt


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master # because *.github.io
  verbose: true
  on:
    branch: publish
